# =========================================
# OLIST DATASET SCHEMA - PRODUCTION READY
# =========================================

# Global Config
target_logic:
  raw_target: review_score
  prediction_target: target
  mapping: {0: "Unsatisfied", 1: "Satisfied"}
  threshold: 4 # Scores < 4 -> 0

# Core Tables
tables:
  orders:
    path: artifacts/data_ingestion/olist_orders_dataset.csv
    columns:
      order_id: object
      customer_id: object
      order_status: object
      order_purchase_timestamp: datetime
      order_estimated_delivery_date: datetime
      order_delivered_customer_date: datetime
    datetime_columns: 
      - order_purchase_timestamp
      - order_estimated_delivery_date
      - order_delivered_customer_date
    constraints:
      order_status_enum: [delivered, shipped, canceled, unavailable, invoiced, processing, created, approved]

  order_items:
    path: artifacts/data_ingestion/olist_order_items_dataset.csv
    columns:
      price: float64
      freight_value: float64
    ranges:
      price: [0.0, 20000.0]
      freight_value: [0.0, 5000.0]

# =========================================
# THE "PRODUCTION HANDSHAKE" FEATURES
# These must match your FastAPI Pydantic Model
# =========================================
inference_features:
  numerical:
    - carrier_handling_time
    - delivery_time_days
    - order_items_count
    - payment_value
    - estimated_delivery_days
    - avg_item_price
    - product_photos_qty
    - is_weekend_order
    - order_hour
    - product_description_lenght
    - total_freight
    - total_price
    - is_late_delivery
    - used_installments
    - payment_installments
    - order_month
    - order_day_of_week
  categorical:
    - product_category_name
    - payment_type
    - customer_state